import random

quick_draw_list = [
    ("France: ","67"),
    ("New Zealand: ","5"),
    ("Nicaragua: ","7"),
    ("Djibouti: ","1"),
    ("Jamaica: ","3"),
    ("Norway: ","5"),
    ("Northern Ireland: ","2"),
    ("United States of America: ","328"),
    ("Germany: ","83"),
    ("Ghana: ","30"),
    ("Canada: ","38"),
    ("Hong Kong: ","7"),
    ("Scotland: ","5"),
    ("Lithuania: ","3"),
    ("South Africa: ","58"),
    ("Egypt: ","98"),
    ("Turkey: ","82"),
    ("Armenia: ","3"),
    ("Azerbaijan: ","10"),
    ("Ukraine: ","42"),
    ("Maldives: ","0.5"),
    ("Australia: ","25"),
    ("Samoa: ","0.2"),
    ("Tonga: ","0.1"),
    ("Ethiopia: ","109"),
    ("Eritrea: ","3"),
    ("Croatia: ","4"),
    ("Poland: ","38"),
    ("Spain: ","47"),
    ("Chile: ","19"),
    ("Argentina: ","44"),
    ("Bolivia: ","11"),
    ("Japan: ","127"),
    ("Cambodia: ","16"),
    ("Laos: ","7"),
    ("Philiippines: ","107")
]
